### PR TITLE
Create an event reader for the isy event stream

### PR DESCRIPTION
**Pull request by bdraco**
Related Issues: automicus#51, automicus#53, shbatm/hacs-isy994#17.

I noticed that isy keep disconnecting the event stream and not reconnecting. Before I start digging in, is this already known?

```shell
2020-04-03 04:24:44 DEBUG (Thread-5) [custom_components.isy994] ISY HEARTBEAT: 2020-04-03T04:24:44.705339
2020-04-03 04:25:09 DEBUG (Thread-5) [custom_components.isy994] ISY HEARTBEAT: 2020-04-03T04:25:09.700665
2020-04-03 04:25:34 DEBUG (Thread-5) [custom_components.isy994] ISY HEARTBEAT: 2020-04-03T04:25:34.698457
2020-04-03 04:25:59 DEBUG (Thread-5) [custom_components.isy994] ISY HEARTBEAT: 2020-04-03T04:25:59.695991
2020-04-03 04:26:24 DEBUG (Thread-5) [custom_components.isy994] ISY HEARTBEAT: 2020-04-03T04:26:24.694949
2020-04-03 04:26:40 DEBUG (Thread-5) [custom_components.isy994.binary_sensor] Sensor Master Bath Motion Sensor turning On via the Primary node sending a DON command
2020-04-03 04:26:40 DEBUG (Thread-5) [custom_components.isy994] ISY Node Control Event: 54 5A 4C 1 NodeProperty('DON': value='1' prec='0' uom='' formatted='1')
2020-04-03 04:26:40 DEBUG (Thread-5) [custom_components.isy994] ISY Updated Node: 54 5A 4C 1
2020-04-03 04:26:40 DEBUG (Thread-5) [custom_components.isy994] ISY Updated Node: 54 5A 4C 5
2020-04-03 04:26:40 DEBUG (Thread-5) [custom_components.isy994] ISY Updated Node: 4D A7 5B 1
```

Debugging:

```shell
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: <?xml version="1.0"?><Event seqnum="1690" sid="uuid:1033"><control>_1</control><action>0</action><node></node><eventInfo><id>3F</id><nsr>200403 19:41:53</nsr></eventInfo></Event>POST reuse HTTP/1.1
```

It gets stuck on this so we are reading part of the next event because its arriving on the socket in the same underlying read call this seems to confuse things and it gets stuck

It should be reading the headers until it gets \r\n\r\n and then it should read up to Content-Length:

```shell
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: POST reuse HTTP/1.1
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: HOST:0.0.0.0:0
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: CONTENT-TYPE:text/xml
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: CONTENT-LENGTH:178
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: Connection: Keep-Alive
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: 
2020-04-03 17:05:20 DEBUG (Thread-2) [custom_components.isy994] watch data: <?xml version="1.0"?><Event seqnum="1690" sid="uuid:1033"><control>_1</control><action>0</action><node></node><eventInfo><id>3F</id><nsr>200403 19:41:53</nsr></eventInfo></Event>POST reuse HTTP/1.1
```

### CODE REVIEW

**Comment by bdraco** [comment]
Submitting for review

This needs more testing before it can merge though.

**Comment by shbatm** [comment]
@OverloadUT -- mind taking a look at these changes when you get a chance?

**Comment by shbatm** [comment]
From @bdraco:
> Also looks like watch is no longer noticeable by the profiler in the event loop
image

Watch is no longer noticeable when the stream chokes? or no longer noticeable with the EventReader?

**Comment by bdraco** [comment]
> Watch is no longer noticeable when the stream chokes? or no longer noticeable with the EventReader?

Its spending so little time in there now that its below the threshold to show up

**Comment by bdraco** [comment]
I think this needs a guard as well
```
2020-04-03 22:36:09 DEBUG (Thread-13) [custom_components.isy994] ISY Updated Program: 0041
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyisy/events.py", line 245, in watch
    self._route_message(message)
  File "/usr/local/lib/python3.7/site-packages/pyisy/events.py", line 97, in _route_message
    self.isy.programs.update_received(xmldoc)
  File "/usr/local/lib/python3.7/site-packages/pyisy/programs/__init__.py", line 187, in update_received
    if pobj.status != new_status:
UnboundLocalError: local variable 'new_status' referenced before assignment
```

**Comment by bdraco** [comment]
So far so good. 3 home assistant instances connected and all going strong.  Usually would have disconnected by now

**Comment by bdraco** [comment]
4th home assistant instance stoped streaming and the other 3 running the new code are still going strong

**Comment by bdraco** [comment]
No disconnects in a few hours now.  seems solid.  Will tail the log overnight as well

**Comment by shbatm** [comment]
Added as `pyisy_beta==2.0.0.dev176` for testing purposes before merge.

**Comment by bdraco** [comment]
Made it though the whole night with all instances still holding the stream, no disconnects/reconnects either.
And since we drain the buffer every time now it also solved the inconstant states where state update would get delayed until another update came along to force the select to unblock

**Comment by shbatm** [comment]
Seems like it's working on my end. I made some minor code tweaks and pushed back to this branch.

I'll let it run through most of today and then merge after work if I don't find any issues.

**Comment by bdraco** [comment]
> Seems like it's working on my end. I made some minor code tweaks and pushed back to this branch.
> 
> I'll let it run through most of today and then merge after work if I don't find any issues.

Changes look good 👍

**Comment by bdraco** [comment]
no disconnects ~ 24 hours. first time this has ever been stable for me

**Pull request merged**
