### PR TITLE
Add uom to send_cmd

### PR DESCRIPTION
**Pull request by simplextech**
Added uom option to send_cmd function.

- Z-Wave devices (Thermostat) require the UOM otherwise they go funky with set points going to MAX

### CODE REVIEW

**Comment by shbatm** [comment]
Before I pull this in, can you please send me what your Z-Wave Thermostat reports out on `/rest/nodes/ZW_ADDR`? I want to also make sure the `climate_setpoint_heat` and `climate_setpoint_cool` functions in `node.py` are also updated appropriately.

**Comment by simplextech** [comment]
Here you go.

`<?xml version="1.0" encoding="UTF-8"?>
<nodeInfo>
    <node flag="128" nodeDefId="UZW000C">
        <address>ZW022_1</address>
        <name>ZW 022 Thermostat</name>
        <family>4</family>
        <parent type="3">21192</parent>
        <type>4.8.6.0</type>
        <enabled>true</enabled>
        <deviceClass>0</deviceClass>
        <wattage>0</wattage>
        <dcPeriod>0</dcPeriod>
        <startDelay>0</startDelay>
        <endDelay>0</endDelay>
        <pnode>ZW022_1</pnode>
        <sgid>1</sgid>
        <devtype>
            <gen>4.8.6</gen>
            <mfg>569.1.1</mfg>
            <cat>140</cat>
        </devtype>
        <ELK_ID>A11</ELK_ID>
        <property id="ST" value="710" formatted="71.0°F" uom="17" prec="1" />
        <property id="CLIMD" value="11" formatted="Energy Save Heat" uom="67" />
        <property id="CLISPC" value="0" formatted="0°C" uom="4" />
        <property id="CLISPH" value="450" formatted="45.0°F" uom="17" prec="1" />
    </node>
    <properties>
        <property id="CLIHCS" value="0" formatted="Idle" uom="66" />
        <property id="CLIMD" value="11" formatted="Energy Save Heat" uom="67" />
        <property id="CLISPC" value="0" formatted="0°C" uom="4" />
        <property id="CLISPH" value="450" formatted="45.0°F" uom="17" prec="1" />
        <property id="ST" value="710" formatted="71.0°F" uom="17" prec="1" />
    </properties>
</nodeInfo>`

**Comment by shbatm** [comment]
[[shbatm/PyISY] Add uom to send_cmd (#8)](https://trello.com/c/P3sq5SZw/237-shbatm-pyisy-add-uom-to-sendcmd-8)

**Comment by simplextech** [comment]
I tried access the Trello card but it's not accessible.  Do you need anymore information from me?

**Comment by shbatm** [comment]
Nope, not at this time. Just haven't been able to get to it yet (real life and all). Trello is just where it is on my to do list.

**Comment by simplextech** [comment]
Great.  I'll be watching as I'm holding off on the ISY Nodeserver release until this is included and I can pull from pypi.

**Comment by shbatm** [comment]
Changes have been merged into PyISY_beta==2.0.0.dev7.  Please let me know if you have any issues.

**Pull request merged**
